### ISSUE TITLE
Fails to activate when package.json is in a non-root location.

### ISSUE THREAD

**Issue by nicholas** [vinkla/autocomplete-tailwind#10]
The activate function looks for package.json explicitly at `atom.project:./`. There are many cases where that's not the case for a project and its conventions. ie: Phoenix apps typically have a package.json stored in ./assets.

I took a look at the Atom APIs and unfortunately there isn't anything magical to locate a file, as far as I could see. I'm guessing a recursive file traversal might be necessary via https://github.com/atom/atom/blob/v1.38.2/src/project.js#L516

Before I even attempt that, I wanted to run this by you @vinkla to get your thoughts on supporting these varied setups. Would this be better addressed via an option for the plugin to choose a non-standard location? Not too keen on that since it'd have to be a per project config.

Also wanted to note, I did start tinkering with this and started with the specs. I added a `project-tailwind-nested/assets/package.json` in `fixtures` and wrote a test similar to the other test cases for testing activation.. and to my surprise it passed. I'm fairly certain those `setTimeout` calls are resulting in false positives. Try changing one of the assertions to `expect(false).toBe(true);` for instance.

Let me know your thoughts and if I find the time, I'll try and support my edge case and hopefully help a few other people out in the process.

**Comment by vinkla** [comment]
Thanks for digging into this! 

I would be open to a pull request adding an option to always show autocompletion. Similar to how the `prettier` package has an option to always format files or just if the package is listed as a dependency in `package.json` file. We could also add a command to quickly toggle the option. 

What do you think?

**Comment by nicholas** [comment]
Perfect, that's a great idea. I'll look into this and send over a PR when I have some free time.

**Comment by vinkla** [comment]
Fixed in #13
