### ISSUE TITLE
Not working with multiple root directories

### ISSUE THREAD

**Issue by mikefogg** [vinkla/autocomplete-tailwind#11]
Hey! Thanks for this autocomplete plugin, honestly, it saves lives.

I noticed one thing that I wanted to point out, it seems like if you have multiple root directories (for me I have an API directory and a React directory as my roots) it will only verify that the _first_ directory has `tailwindcss` as a dependency. If the API directory is the top directory in the list, it won't work. If I move it so my React directory is first (which has tailwindcss in `package.json`) things work great!

We may have to change it so it checks to see if _any_ of your root directories have it? Or maybe this is expected behavior :) 

Thanks again!

**Comment by vinkla** [comment]
I'm glad you like the package!

I guess this is somewhat related to #10 where we discussed adding an option in the package settings to always show autocompletion.

Quick question; are the directories added as project folders or sub-directories within the root project in Atom?

**Comment by vinkla** [comment]
Fixed in #13
