### ISSUE TITLE
I can't get this to work at all

### ISSUE THREAD

**Issue by 1000martians** [vinkla/autocomplete-tailwind#12]
I installed it through Atom's packages. Restarted atom and the autocomplete is still not working.

**Comment by vinkla** [comment]
Did you install the `tailwindcss` package using non in your project?

**Comment by 1000martians** [comment]
No I did not. I downloaded it using the search function within Atom just like every other package I’ve downloaded. Do I have to install this one differently?

Mark Del Mar
Photographer
markdelmar.com

**Comment by vinkla** [comment]
Yes, take a look at the README.

**Comment by eyaltoledano** [comment]
Hey there, I installed it with npm `apm install autocomplete-tailwind` from my project folder; it seems to be installed but I'm not seeing any suggestions. Feels like I didn't set it up right though I followed the readme 😬
