### ISSUE TITLE
Doesn't work with custom tailwind packages

### ISSUE THREAD

**Issue by Cosbgn** [vinkla/autocomplete-tailwind#15]
The tool doesn't work with custom tailwind packages, I for example use [@nuxtjs/tailwindcss](https://github.com/nuxt-community/nuxt-tailwindcss) - Deactivating the setting "use only if tailwind is found in the packages" makes it work again, but then it works everywhere.

It would be great if we could add custom packages or maybe it could just look for the word "tailwindcss" in the packages

**Comment by vinkla** [comment]
Do you have the `taiwindcss` package listed in your `package.json` file=

**Comment by Cosbgn** [comment]
@vinkla no I have "@nuxtjs/tailwindcss": "^1.1.2", in my package, that's why it's not working. If I would only have tailwindcss it would work, but that's not the case. I'm suggesting that it could just look for the word tailwind not the exact package

**Comment by vinkla** [comment]
You're welcome to send a pull request. I currently don't have any time to implement this feature.
