### ISSUE TITLE
Autocomplete with .vue files 

### ISSUE THREAD

**Issue by desaintflorent** [vinkla/autocomplete-tailwind#3]
Hi there ! 
Thanks for this tailwind autocomplete plugin.
I was wondering how I can use it in vue files ? right now it's only working on .html file.

**Comment by vinkla** [comment]
Hey @desaintflorent! I'm glad you like it 😃 

I agree that would be a great addition. Support has [also been requested for JSX](https://twitter.com/crysfel/status/1095738586010447872). I've tried adding JSX support without luck. I'm not comfortable with the [grammar system](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/) in Atom. If you or anyone else would submit a pull request it'd been great!

**Comment by desaintflorent** [comment]
Yes would be definitely great ! Would I love to help, but I don't know anything about grammar system too :/

**Comment by vinkla** [comment]
I've published a new version which should solve this issue. Please update and see if it works.
https://github.com/vinkla/autocomplete-tailwind/issues/4#issuecomment-472813987
